In [132]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.datasets import load_diabetes

In [133]:
X,y = load_diabetes(return_X_y=True)

In [134]:
X

array([[ 0.03807591,  0.05068012,  0.06169621, ..., -0.00259226,
         0.01990749, -0.01764613],
       [-0.00188202, -0.04464164, -0.05147406, ..., -0.03949338,
        -0.06833155, -0.09220405],
       [ 0.08529891,  0.05068012,  0.04445121, ..., -0.00259226,
         0.00286131, -0.02593034],
       ...,
       [ 0.04170844,  0.05068012, -0.01590626, ..., -0.01107952,
        -0.04688253,  0.01549073],
       [-0.04547248, -0.04464164,  0.03906215, ...,  0.02655962,
         0.04452873, -0.02593034],
       [-0.04547248, -0.04464164, -0.0730303 , ..., -0.03949338,
        -0.00422151,  0.00306441]])

In [135]:
X.shape

(442, 10)

In [136]:
y.shape

(442,)

In [137]:
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression

In [138]:
X_train , X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 10)

In [139]:
y_train.shape

(353,)

In [140]:
X_train.shape

(353, 10)

In [141]:
lr= LinearRegression()

In [142]:
lr.fit(X_train,y_train)

LinearRegression()

In [143]:
from sklearn.metrics import r2_score

In [146]:
y_pred = lr.predict(X_test)

In [147]:
lr.predict(X_test[0].reshape(1,-1)) # for shape (1,10)

array([148.09458516])

In [148]:
print("r2 score: ",r2_score(y_test,y_pred))

r2 score:  0.5341988244945843


Code from scratch

In [149]:
class linearRegression:
    def __init__(self):
        self.coeff = None
        self.intercept = None
    def fit(self, X_train , y_train):
        X_train = np.insert(X_train,0,1,axis=1)
        
        # calcuate the coeffs
        betas = np.linalg.inv(np.dot(X_train.T,X_train)).dot(X_train.T).dot(y_train)
        self.intercept_ = betas[0]
        self.coef_ = betas[1:]
        print(betas.shape)
    def predict(self, X_test):
        y_pred = np.dot(X_test,self.coef_) + self.intercept_ #y_pred = b0 + b1x11 + b2x12 +.....+ bmx1m
        return y_pred

In [150]:
lr = linearRegression()

In [151]:
lr.fit(X_train, y_train)

(11,)


In [152]:
y_pred_new = lr.predict(X_test)

In [153]:
r2_score(y_test,y_pred_new)

0.5341988244945839

In [154]:
X_test.shape

(89, 10)

In [155]:
lr.predict(X_test[0].reshape(1,-1)) # for shape (1,10)

array([148.09458516])